#pragma once

#include <cstddef>
#include <string_view>

inline constexpr std::string_view AUTOGENERATED_PREFIX = R"#(
# #######################################################################################
# AUTOGENERATED ZESTWM CONFIG.
# EDIT THIS CONFIG ACCORDING TO THE ZESTWM DOCUMENTATION.
# #######################################################################################

autogenerated = 1 # remove this line to remove the warning

)#";

inline constexpr unsigned char    EXAMPLE_CONFIG_BYTES[] = {
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wc23-extensions"
#endif
#embed "../examples/zestwm.conf"
#if defined(__clang__)
#pragma clang diagnostic pop
#endif
};

inline constexpr std::size_t EXAMPLE_CONFIG_SIZE = sizeof(EXAMPLE_CONFIG_BYTES);
